# Generated by Django 5.0.2 on 2024-02-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_chessgame_is_white_move"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chessgame",
            name="move_history",
        ),
        migrations.AlterField(
            model_name="chessgame",
            name="fen",
            field=models.CharField(
                default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                max_length=255,
            ),
        ),
    ]
