# Generated by Django 5.0.2 on 2024-02-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_remove_chessgame_move_history_alter_chessgame_fen"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="move_history",
            field=models.JSONField(default=list),
        ),
    ]
