# Generated by Django 5.0.2 on 2024-02-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_chessgame_black_rematch_chessgame_white_rematch"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="fen",
            field=models.TextField(default=""),
        ),
    ]
