# Generated by Django 5.0.2 on 2024-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_chessgame_fen"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="move_increment",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chessgame",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chessgame",
            name="total_game_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
