# Generated by Django 5.0.2 on 2024-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0010_chessgame_move_increment_chessgame_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="black_move_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chessgame",
            name="white_move_count",
            field=models.IntegerField(default=0),
        ),
    ]
