# Generated by Django 5.0.2 on 2024-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0011_chessgame_black_move_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chessgame",
            name="black_move_count",
        ),
        migrations.RemoveField(
            model_name="chessgame",
            name="white_move_count",
        ),
        migrations.AddField(
            model_name="chessgame",
            name="black_user_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chessgame",
            name="last_move_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chessgame",
            name="white_user_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
