# Generated by Django 5.0.2 on 2024-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0012_remove_chessgame_black_move_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="black_user_end_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chessgame",
            name="white_user_end_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
