# Generated by Django 5.0.2 on 2024-02-21 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0013_alter_chessgame_black_user_end_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chessgame",
            old_name="black_user_end_time",
            new_name="black_user_total_time",
        ),
        migrations.RenameField(
            model_name="chessgame",
            old_name="white_user_end_time",
            new_name="white_user_total_time",
        ),
    ]
