# Generated by Django 5.0.2 on 2024-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0015_remove_chessgame_black_user_total_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="black_user_remaining_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chessgame",
            name="white_user_remaining_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
