# Generated by Django 5.0.2 on 2024-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0016_chessgame_black_user_remaining_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="black_draw",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chessgame",
            name="white_draw",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
