# Generated by Django 5.0.2 on 2024-02-26 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0017_chessgame_black_draw_chessgame_white_draw"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="unique_link",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=36, unique=True
            ),
        ),
    ]
