# Generated by Django 5.0.2 on 2024-03-07 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0018_chessgame_unique_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="unique_link",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
